const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'../../..');const asset=path.join(root,'30_设计与素材库/UI设计/20260921_V2B2样片');const out=path.join(root,'40_项目交接文档/验证记录/V2B2_场景与语言');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_BIN,headless:true,args:['--enable-unsafe-swiftshader']});const checks=[],errors=[];const check=(name,value)=>{assert(value,name);checks.push(name)};
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+asset+'/index.html');await p.waitForTimeout(400);
check('Unknown region defaults to English',await p.evaluate(()=>studyQA.language==='en'));check('No Chinese visible on English home',!/[\u4e00-\u9fff]/.test(await p.locator('#phone').innerText()));check('No home title or cleared-level progress',await p.locator('#home h1,#home .wordmark,#home .reward-progress').count()===0);
await p.locator('#region').selectOption('china');check('China region in automatic mode selects Chinese',await p.evaluate(()=>studyQA.language==='zh'));check('Chinese home has no English words',!/[a-zA-Z]/.test(await p.locator('#phone').innerText()));
await p.locator('[data-action="settings"]').click();await p.locator('#language').selectOption('en');check('Manual English overrides China',await p.evaluate(()=>studyQA.language==='en'&&studyQA.preference==='en'));await p.reload();check('Manual language persists on reload',await p.evaluate(()=>studyQA.language==='en'&&studyQA.preference==='en'));
await p.locator('[data-action="settings"]').click();await p.locator('#language').selectOption('zh');await p.locator('#region').selectOption('other');check('Manual Chinese overrides other region',await p.evaluate(()=>studyQA.language==='zh'));await p.locator('#language').selectOption('auto');check('Other region defaults to English',await p.evaluate(()=>studyQA.language==='en'));await p.locator('#region').selectOption('china');check('Automatic can be restored',await p.evaluate(()=>studyQA.language==='zh'));await p.locator('#region').selectOption('unknown');await p.locator('.panel>header [data-action="close"]').click();
await p.locator('#motion').uncheck();await p.waitForTimeout(100);const n=await p.evaluate(()=>studyQA.homeView.draws);await p.waitForTimeout(150);check('Motion toggle stops redraw',n===await p.evaluate(()=>studyQA.homeView.draws));
await p.locator('#phone').screenshot({path:path.join(out,'Home_EN_390x844.png')});
const a=await p.locator('#home-boat').screenshot();await p.locator('[data-action="nextship"]').click();const z=await p.locator('#home-boat').screenshot();check('Two geometric models render differently',!a.equals(z)&&await p.evaluate(()=>studyQA.variant===1));await p.locator('#phone').screenshot({path:path.join(out,'Home_Explorer_EN_390x844.png')});await p.locator('#waves').uncheck();check('Water ripples can be disabled',await p.locator('.ripples').isHidden());await p.locator('#phone').screenshot({path:path.join(out,'Home_NoRipples_EN_390x844.png')});await p.locator('[data-action="previous"]').click();await p.locator('#waves').check();
await p.locator('#motion').check();await p.waitForTimeout(100);check('Motion resumes on home',await p.evaluate(()=>studyQA.motionActive));await p.locator('[data-action="collection"]').click();await p.waitForTimeout(100);check('Modal pauses showcase motion',!await p.evaluate(()=>studyQA.motionActive));
for(let t=0;t<4;t++){await p.locator('[data-tab="'+t+'"]').click();const text=await p.locator('#modal-content').innerText();check('Category '+t+' acquisition and slots',t===0?text.includes('Draw to collect')&&text.includes('COMBAT LOADOUT'):text.includes('Clear levels to unlock')&&!text.includes('COMBAT LOADOUT'));check('English category '+t+' is monolingual',!/[\u4e00-\u9fff]/.test(await p.locator('#phone').innerText()));if(t===0||t===2)await p.locator('#phone').screenshot({path:path.join(out,'Collection_'+t+'_EN_390x844.png')});}
await p.locator('.panel>header [data-action="close"]').click();await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(100);check('System reduced motion stops showcase',!await p.evaluate(()=>studyQA.motionActive));await p.emulateMedia({reducedMotion:'no-preference'});
for(const size of [{width:390,height:844},{width:360,height:640}]){await p.setViewportSize(size);for(const lang of ['en','zh']){await p.locator('[data-review="home"]').click();await p.locator('[data-action="settings"]').click();await p.locator('#language').selectOption(lang);await p.locator('.panel>header [data-action="close"]').click();await p.locator('#motion').uncheck();for(const screen of ['home','game','result']){await p.locator('[data-review="'+screen+'"]').click();await p.waitForTimeout(80);const text=await p.locator('#phone').innerText();check(`${size.width} ${lang} ${screen} single language`,lang==='en'?!/[\u4e00-\u9fff]/.test(text):!/[a-zA-Z]/.test(text));if(screen==='result'){check(`${size.width} ${lang} result model does not cover reward text`,await p.evaluate(()=>{const model=document.querySelector('.result-ship').getBoundingClientRect(),coins=document.querySelector('.reward-coins').getBoundingClientRect(),target=document.querySelector('.reward-track').getBoundingClientRect();return model.top>=coins.bottom&&model.bottom<=target.top;}));}const overlap=await p.locator('#'+screen+' button:visible').evaluateAll(es=>{const rs=es.map(e=>e.getBoundingClientRect());return rs.some((a,i)=>rs.slice(i+1).some(b=>Math.min(a.right,b.right)-Math.max(a.left,b.left)>1&&Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)>1))});check(`${size.width} ${lang} ${screen} buttons do not overlap`,!overlap);const boxes=await p.locator('#'+screen+' button:visible').evaluateAll(es=>es.map(e=>{const r=e.getBoundingClientRect(),phone=document.querySelector('#phone').getBoundingClientRect();return {w:r.width,h:r.height,inside:r.left>=phone.left-1&&r.right<=phone.right+1&&r.top>=phone.top-1&&r.bottom<=phone.bottom+1}}));check(`${size.width} ${lang} ${screen} controls at least 44px and inside`,boxes.every(x=>x.w>=44&&x.h>=44&&x.inside));if(size.width===360||lang==='zh'||screen!=='home')await p.locator('#phone').screenshot({path:path.join(out,`${screen}_${lang}_${size.width}x${size.height}.png`)});}}
}
await p.setViewportSize({width:390,height:844});await p.locator('[data-review="ten"]').click();await p.locator('[data-action="nextlevel"]').click();check('L10 with unavailable next stays on result',await p.evaluate(()=>studyQA.screen==='result'));await p.locator('#phone').screenshot({path:path.join(out,'Level10_StaysOnResult_ZH.png')});await p.locator('#next-available').check();await p.locator('[data-action="nextlevel"]').click();check('Available-next branch acknowledged without invented level',await p.locator('#toast').innerText()==='目录衔接示意：下一关入口可用。');
await p.locator('[data-review="deadlock"]').click();check('Deadlock cue is nonmodal',await p.locator('#modal').isHidden()&&await p.locator('.deadlock').isVisible());check('Deadlock cue does not intercept input',await p.locator('.deadlock').evaluate(e=>getComputedStyle(e).pointerEvents==='none'));await p.locator('#phone').screenshot({path:path.join(out,'Deadlock_Nonmodal_ZH.png')});
check('Original layout matches source JSON exactly',JSON.stringify(await p.evaluate(()=>studyQA.originalLevel))===JSON.stringify(JSON.parse(fs.readFileSync(path.join(root,'10_开发工作区/TideboundFleet_Unity/Assets/Tidebound/Config/LevelPrototypes/Phase5R_TenLevelCandidates/P5R_Ten_003.json'),'utf8'))));check('Original layout is unchanged 80 boats',await p.evaluate(()=>studyQA.originalLevel.ships.length===80));check('WebGL has no error',await p.evaluate(()=>[studyQA.homeView,studyQA.boardView,studyQA.resultView].every(v=>v.gl.getError()===0)));check('No script errors',errors.length===0);
await p.locator('[data-review="home"]').click();await p.locator('[data-action="settings"]').click();await p.locator('#language').selectOption('zh');await p.locator('#phone').screenshot({path:path.join(out,'Settings_ZH_390x844.png')});await p.locator('#language').selectOption('en');await p.locator('#phone').screenshot({path:path.join(out,'Settings_EN_390x844.png')});const cnContext=await b.newContext({locale:'zh-CN'});const cnPage=await cnContext.newPage();await cnPage.goto('file://'+asset+'/index.html');check('Chinese system language alone does not imply China region',await cnPage.evaluate(()=>studyQA.language==='en'));await cnContext.close();await p.goto('file://'+asset+'/components.html');await p.setViewportSize({width:1200,height:1040});await p.screenshot({path:path.join(out,'Components_EN.png'),fullPage:true});
fs.writeFileSync(path.join(out,'browser-checks.json'),JSON.stringify({date:'2026-09-21',checks,errors,scope:'Offline browser study. Simulated region only. No Unity or real device acceptance.'},null,2)+'\n');console.log(checks.length+' checks passed');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
